name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Write key
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
          echo releaseStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo releaseKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
          echo releaseKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo releaseStoreFile='key.jks' >> gradle.properties
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > key.jks
          fi

      - name: Build the app
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assemble --stacktrace

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-build-apk
          path: app/build/outputs/apk

